<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Hytale.Qa.Contracts\Hytale.Qa.Contracts.csproj" />
    <ProjectReference Include="..\Hytale.Qa.Windows\Hytale.Qa.Windows.csproj" />
  </ItemGroup>
</Project>
